apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-event-listener
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-event-listener
    spec:
      containers:
        - name: spring-boot-event-listener
          image: 'gcr.io/gcloud-example-263116/spring-boot-event-listener:v3'
          command: ["sh","-c"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: '50m'
              memory: "64Mi"
            limits:
              cpu: '100m'
              memory: "512Mi"
          volumeMounts:
            - name: heap-dumps
              mountPath: /tmp
      volumes:
        - name: heap-dumps
          emptyDir: {}